### PR TITLE
DigitalOceanCI

### PR DESCRIPTION
**Pull request by bordenit**
The As-Is for this PR and this repo....

For this PR to work....
1. Get a DockerHub Account, if you do not have one. IT IS FREE :).
2. Get a Domain Name if you do not have one. I have a few I pay for but never use if you want me to host some DNS records for testing.
3. Create a Digital Ocean Droplet. Under Marketplace when creating a droplet in Digital Ocean, there is a docker option. You only need the $5/month droplet for this repo.
4.  Update DNS A record to point to Digital Ocean IP.
5. Wait between 5 minutes and 48 hours for DNS to replicate.
6. Update these GitHub Secrets
Untitled

7. Change domain name in test/Integration/Web/appsettings.Production.json 

**Expected Result**
Once all those things are done, it will deploy the sample application to DigitalOcean droplet on each pull request and check the HTTPS page for the commit that matches the change.
serviceno screenshot

### CODE REVIEW

**Comment by natemcmaster** [comment]
Thanks for opening this pull request @bordenit! You've given me some good ideas for how we can add real integrated testing CI for this project.

I have a few questions about what you're proposing. I'm not super familiar with ansible, digital ocean, or github workflows (thought I'd like to learn). How hard would it be to make this example work with Azure Dev Ops, Container Registry, and Container Instances instead? I was hoping to avoid running integration tests like this automatically as it seems like a potential hazard to automatically give access to all pull requests to mess with my Docker Hub account and/or run up my Azure or Digital Ocean bill. I was thinking we could address this by using Azure Dev Ops comment triggers - https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers

Thoughts?

**Comment by bordenit** [comment]
Yes, it does make sense. I haven’t used those Azure services in a few years, but it’s just building, pushing, and pulling a container. If you could get a static ip to the server that builds it, then you could do it all on the same server without a container registry. Maybe you could make a tunnel with ngrok inside the pipeline itself as another alternative. I didn’t play with ngrok, because a tunnel to my house made me nervous and it was cheap to use a real domain.

**Comment by bordenit** [comment]
Here is just the image publishing part of it.

```yaml
jobs:
- job: dockerBuild
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      Windows:
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)
  steps:
  - task: Docker@2
    displayName: Login to Container Registry
    inputs:
      command: login
      containerRegistry: myRegistry
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: myRegistry
      tags: |
        $(vmImage)
```

**Comment by natemcmaster** [comment]
Been looking for a way to enable manually triggered pull request checks, but only if a contributor on this project triggers it. This is the closest thing I've found so far: https://github.com/marketplace/actions/slash-command-dispatch
https://blog.stephencleary.com/2020/04/github-actions-pull-request-staging-environments-part-2-slash-commands.html

> Still reading about Azure Container Instances, but I imagine it will cost more than DigitalOcean.

I have some unused Azure credit which should cover this cost, so want to use that up first. Can move to DO later once that dries up, but that won't happen for a while. :)

**Comment by bordenit** [comment]
I’ll make it work with Azure after the holiday weekend. Just need to figure out the container instances. Maybe the A record [or alternative DNS record] pointing to a load balancer with a container instance you can start up and shutdown dynamically in the backend would be more cost effective. You only would need the containers o long enough to test. Not sure yet, but it sounds interesting.

**Comment by natemcmaster** [comment]
Azure Containers Instances should have a DNS record already without needing to register it with a customer domain. For example, I set this up to test some stuff a few weeks ago: letsencrypt-test2.centralus.azurecontainer.io. 

Thanks for your diligence in looking into this! Sincerely appreciate the help :D

**Comment by bordenit** [comment]
I thought I could stomach reactivating my Azure account, but I can't bring myself to do that. It's just a personal thing I guess. If anyone else wants to pick up this integration testing up, then feel free. It looks like it's mostly a point and click drill in Azure DevOps. I'm going to close this PR, as the code changes offered in it are mostly Ansible, GitHub Actions, Docker Hub, and Digital Ocean related.

**Pull request closed without merging**
